repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint

- repo: https://github.com/golangci/golangci-lint
  rev: v1.46.2
  hooks:
  - id: golangci-lint
    args:
    - --config=./.golangci-precommit.yml
    - --deadline=5m
