---
version: 2.1

orbs:
  go: circleci/go@1.10.0

workflows:
  ci:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - /.*/
      - test:
          requires:
            - lint
          filters:
            branches:
              only:
                - /.*/

jobs:
  lint:
    docker:
      # we lint with pre-commit hence a python based image
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: install pre-commit
          command: pip install pre-commit
      - run:
          command: |
              sudo mkdir -p /usr/local/go
              sudo chown -R $(whoami): /usr/local/go
      - go/install:
          version: "1.20"
          cache: false
      - run:
          name: lint source code
          command: make lint

  test:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run:
          name: run unit tests
          command: make test
