---
version: 2.1

orbs:
  go: circleci/go@1.7.1
  snyk: snyk/snyk@1.2.3

workflows:
  ci:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - /.*/
      - test:
          requires:
            - lint
          filters:
            branches:
              only:
                - /.*/
      - scan:
          filters:
            branches:
              only:
                - /.*/

jobs:
  lint:
    docker:
      # we lint with pre-commit hence a python based image
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: install pre-commit
          command: pip install pre-commit
      - run:
          command: |
              sudo mkdir -p /usr/local/go
              sudo chown -R $(whoami): /usr/local/go
      - go/install:
          version: 1.18.2
          cache: false
      - run:
          name: lint source code
          command: make lint

  test:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - run:
          name: run unit tests
          command: make test

  scan:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      # push scan results to the Snyk UI if we on the default branch
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - snyk/scan:
                fail-on-issues: true
                organization: "cbaa4672-dc38-4a7d-b797-e350dbdf029e" #Open Source Snyk Organization
                monitor-on-build: true
      # don't push scan results to the Snyk UI if we're not on the default branch
      - when:
          condition:
            not:
              equal: [ main, << pipeline.git.branch >> ]
          steps:
            - snyk/scan:
                fail-on-issues: true
                organization: "cbaa4672-dc38-4a7d-b797-e350dbdf029e" #Open Source Snyk Organization
                monitor-on-build: false

